### PR TITLE
Fix #38 new

### LINKED ISSUE #38: Mockup print UI
Mockup this window on the new map viewer

image

### PR DESCRIPTION
**Pull request by andreabiagi**
fix #38 print panel

index.html updated

nav mini map added

Classes of "select" updated

### CODE REVIEW

**Comment by Gnafu** [comment]
Are you missing the "checked" icon?

**Comment by offtherailz** [comment]
seems that something went wrong. How did you tested it? I checked on raw git and it seems ugly.

https://rawgit.com/andreabiagi/MapStore2-theme/panelprint/samples/map/print-panel.html

**Comment by offtherailz** [comment]
Sorry, my fault. I looked at the wrong branch (printpanel). 
The correct rawgit to look at is https://rawgit.com/andreabiagi/MapStore2-theme/f39a08d9744bcfebb25a7dacd5c7eea124882fa6/samples/map/print-panel.html

**Comment by Gnafu** [comment]
@andreabiagi I see many of the changes in this pull request are also in others, should we close this one?

**Comment by andreabiagi** [comment]
This is not the last version of "panel-print". I sent it in "catalog and
panel-print" yesterday.
Did you see "manager" page?

Saluti, Andrea.

_web_
_www.chefstudio.it http://www.chefstudio.it/_
_www.andreabiagi.com_ http://www.andreabiagi.com/

_phone: *+39 328 25 57 115
*skype: *andrea.biagi88
*P.I._ : 02374680466
*address: *via borgo biagi 59, Pietrasanta (LU), Italy

2016-06-16 9:48 GMT+02:00 Lorenzo Natali notifications@github.com:

**Pull request closed without merging**
