### PR TITLE
fix#37 home welcome 

### LINKED ISSUE #37: Improve the welcome page
- [ ] Move the GeoSolutions Logo on top and remove the mapstore 2 logo inside the page. 
- [ ] Remove "New User Interface" in the banner. Reduce the height properly to let more space for maps. 
- [ ] Move the search bar on the center of the image.
- [ ] The description has the same width of the maps

image

### PR DESCRIPTION
**Pull request by andreabiagi**
fix#37

The description hasn't the same width of the maps.
In this way the readability is improved.

### CODE REVIEW

**Comment by Gnafu** [comment]
Hi, this pull request closes only one task out of four for the issue #37 .
Do you plan to send a pull request for each task or to update this one?

**Comment by andreabiagi** [comment]
image

I think I've fix every task oh #37 . Do you see the same layout of the image? 
maybe i committed  wrong files?!

**Comment by Gnafu** [comment]
My bad, I was looking at the wrong page.
The only issue i got is on Firefox, I see a "j" in the search bar instead of the icon.

**Comment by Gnafu** [comment]
It looks like it is a security constraint in Firefox, we should be carefull with relative paths when merging the theme.
https://stackoverflow.com/questions/2856502/css-font-face-not-working-with-firefox-but-working-with-chrome-and-ie

**Pull request merged**
